export const ErrorCode = {
  INVALID_INPUT: "INVALID_INPUT",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  POLICY_VIOLATION: "POLICY_VIOLATION",
  KILL_SWITCH_ACTIVE: "KILL_SWITCH_ACTIVE",
  INVALID_APPROVAL_TOKEN: "INVALID_APPROVAL_TOKEN",
  EXPIRED_APPROVAL_TOKEN: "EXPIRED_APPROVAL_TOKEN",
  MARKET_CLOSED: "MARKET_CLOSED",
  INSUFFICIENT_BUYING_POWER: "INSUFFICIENT_BUYING_POWER",
  FEATURE_DISABLED: "FEATURE_DISABLED",
  NOT_SUPPORTED: "NOT_SUPPORTED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ToolError {
  code: ErrorCode;
  message: string;
  details?: unknown;
}

export class NightwatcherError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly details?: unknown
  ) {
    super(message);
    this.name = "NightwatcherError";
  }

  toToolError(): ToolError {
    return {
      code: this.code,
      message: this.message,
      details: this.details,
    };
  }
}

export function createError(
  code: ErrorCode,
  message: string,
  details?: unknown
): NightwatcherError {
  return new NightwatcherError(code, message, details);
}

import type { Env } from "../env.d";
import { generateId } from "./utils";
import { createGitHubIssue } from "./github";

export async function logError(
  env: Env,
  module: string,
  event: string,
  error: Error | unknown,
  severity: "info" | "warn" | "error" | "fatal" = "error",
  context?: Record<string, any>
): Promise<void> {
  const id = generateId();
  const ts = Date.now();
  const errorMessage = error instanceof Error ? error.message : String(error);
  const errorStack = error instanceof Error ? error.stack : undefined;
  
  // Extract traceId from context if available
  const trace_id = context?.traceId || context?.trace_id || null;

  const payload = JSON.stringify({
    message: errorMessage,
    stack: errorStack,
    context
  });

  console.error(`[${severity.toUpperCase()}] [${module}] ${event}: ${errorMessage}`, context || "");

  try {
    // Write to D1 error_log
    const query = `
      INSERT INTO error_log (id, ts, module, event, severity, trace_id, payload)
      VALUES (?, ?, ?, ?, ?, ?, ?)
    `;
    
    // We fetch the D1 binding manually to avoid circular dependencies in some paths
    if (env.DB) {
      await env.DB.prepare(query).bind(id, ts, module, event, severity, trace_id, payload).run();
    }

    // Agentic Bug Loop: Conditionally escalate fatal errors to GitHub Issues
    if (severity === "fatal" && env.GITHUB_TOKEN) {
      const issueTitle = `[FATAL] ${module}: ${event}`;
      const issueBody = `
## Fatal Error Detected in \`${module}\`

**Event:** ${event}
**Timestamp:** ${new Date(ts).toISOString()}
**Log ID:** ${id}

### Error Message
\`\`\`
${errorMessage}
\`\`\`

### Context
\`\`\`json
${JSON.stringify(context || {}, null, 2)}
\`\`\`

### Stack Trace
\`\`\`
${errorStack || "No stack trace available"}
\`\`\`

---
*Auto-generated by Nightwatcher.OS Error Logger. Observer agent will review this shortly.*
      `;
      
      // Replace LNSTT369/VALKYRIE with the actual repo if dynamic, but keeping static for now.
      const repoPath = "LNSTT369/VALKYRIE"; 
      
      try {
        await createGitHubIssue(env.GITHUB_TOKEN, repoPath, issueTitle, issueBody, ["bug", "fatal-error"]);
        console.log(`Successfully escalated fatal error to GitHub Issue in ${repoPath}`);
      } catch (ghErr) {
        console.error("Failed to escalate fatal error to GitHub:", ghErr);
      }
    }
  } catch (dbErr) {
    console.error("Failed to write to error_log D1 table:", dbErr);
  }
}
